# Generated by Django 3.2.18 on 2023-08-25 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_rename_image_userprofile_p_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='p_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
